# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

my_usize_r_name <- new.env(parent = emptyenv())

my_usize_r_name$new <- function(x) .Call(wrap__my_usize_r_name__new, x)

my_usize_r_name$print <- function() invisible(.Call(wrap__my_usize_r_name__print, self))

#' @export
`$.my_usize_r_name` <- function (self, name) { func <- my_usize_r_name[[name]]; environment(func) <- environment(); func }

#' @export
`[[.my_usize_r_name` <- `$.my_usize_r_name`


# nolint end
